version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  services:
    build:
      context: ./services
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./services:/app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - services
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
    driver: bridge
