version: '3.8'

services:
  services:
    build:
      context: ./services
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - services

