version: '3.8'

services:
  services:
    build:
      context: ./services
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - services
    volumes:
      - ./backend/database.db:/app/database.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - services
