version: '3.8'

services:
  services:
    image: sleepifoxx/services:latest
    ports:
      - "8001:8001"

  backend:
    image: sleepifoxx/backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - services
    volumes:
      - ./backend/database:/app/database

  frontend:
    image: sleepifoxx/frontend:latest
    ports:
      - "80:3000"
    depends_on:
      - services
      - backend
